{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":137285340,"authorName":"Gordon Mohr","from":"Gordon Mohr &lt;gojomo@...&gt;","profile":"gojomo","replyTo":"LIST","senderId":"Luv4Nph7keJN0U7DgwckkiNWKdailiKwWfa0OlDGgofq7e5wQu_USAeaws5pc1UOCl_L6X3PChSnaIN0obqetkY7wjKqL3A","spamInfo":{"isSpam":false,"reason":"6"},"subject":"Re: [archive-crawler] Re: H3: Crawl progress halted, ConcurrantModificationException","postDate":"1282338674","msgId":6691,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PDRDNkVFRjcyLjYwMTAxMDdAYXJjaGl2ZS5vcmc+","inReplyToHeader":"PDAyMmQwMWNiM2ZhNSQzOTkxNzlhMCRhY2I0NmNlMCRAYXJjaGl2ZS5vcmc+","referencesHeader":"PGk0MXZ1ays2bTZqQGVHcm91cHMuY29tPiA8NEM2QzYwQTQuMTA2MDcwNUBhcmNoaXZlLm9yZz4gPDAyMmQwMWNiM2ZhNSQzOTkxNzlhMCRhY2I0NmNlMCRAYXJjaGl2ZS5vcmc+"},"prevInTopic":6687,"nextInTopic":0,"prevInTime":6690,"nextInTime":6692,"topicId":6676,"numMessagesInTopic":5,"msgSnippet":"Do you have a full stack of the ConcurrentModificationException itself, so it s clear what data structure is throwing the exception? (It should be in the","rawEmail":"Return-Path: &lt;gojomo@...&gt;\r\nX-Sender: gojomo@...\r\nX-Apparently-To: archive-crawler@yahoogroups.com\r\nX-Received: (qmail 8354 invoked from network); 20 Aug 2010 21:11:24 -0000\r\nX-Received: from unknown (66.196.94.106)\n  by m10.grp.re1.yahoo.com with QMQP; 20 Aug 2010 21:11:24 -0000\r\nX-Received: from unknown (HELO relay02.pair.com) (209.68.5.16)\n  by mta2.grp.re1.yahoo.com with SMTP; 20 Aug 2010 21:11:24 -0000\r\nX-Received: (qmail 52738 invoked from network); 20 Aug 2010 21:11:14 -0000\r\nX-Received: from 208.70.27.190 (HELO silverbook.local) (208.70.27.190)\n  by relay02.pair.com with SMTP; 20 Aug 2010 21:11:14 -0000\r\nX-pair-Authenticated: 208.70.27.190\r\nMessage-ID: &lt;4C6EEF72.6010107@...&gt;\r\nDate: Fri, 20 Aug 2010 14:11:14 -0700\r\nUser-Agent: Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; en-US; rv:1.9.2.8) Gecko/20100802 Thunderbird/3.1.2\r\nMIME-Version: 1.0\r\nTo: =?ISO-8859-1?Q?Kristinn_Sigur=F0sson?= &lt;kris@...&gt;\r\nCc: archive-crawler@yahoogroups.com\r\nReferences: &lt;i41vuk+6m6j@...&gt; &lt;4C6C60A4.1060705@...&gt; &lt;022d01cb3fa5$399179a0$acb46ce0$@...&gt;\r\nIn-Reply-To: &lt;022d01cb3fa5$399179a0$acb46ce0$@...&gt;\r\nContent-Type: text/plain; charset=ISO-8859-1; format=flowed\r\nContent-Transfer-Encoding: 8bit\r\nX-eGroups-Msg-Info: 1:6:0:0:0\r\nFrom: Gordon Mohr &lt;gojomo@...&gt;\r\nSubject: Re: [archive-crawler] Re: H3: Crawl progress halted, ConcurrantModificationException\r\nX-Yahoo-Group-Post: member; u=137285340; y=n8Fs26L6Qi4dVM3G6fdUOECQLuwkdTJOxPr0H1__stKq\r\nX-Yahoo-Profile: gojomo\r\n\r\nDo you have a full stack of the ConcurrentModificationException itself, \nso it&#39;s clear what data structure is throwing the exception? (It should \nbe in the _out.log coincident in time with the reports in the job.log.)\n\nThis latest NegativeArraySizeException appears to be a problem in some \nthird-party code... but because it throws an exception caught outside \nall processing-chains, might be interfering with (or revealing a bug in) \nthe intended &#39;atomicity&#39; of DispositionProcessing with regard to \ncheckpointing.\n\n- Gordon @ IA\n\nOn 8/19/10 6:48 AM, Kristinn Sigurï¿½sson wrote:\n&gt;\n&gt;\n&gt;&gt; Checkpoints should be much faster in H3 -- and definitely not trigger any\n&gt;&gt; ConcurrentModificationExceptions. If you can dig up representative deeper\n&gt;&gt; stacks from the exceptions in the _out.log, and attach to a new issue,\n&gt; I&#39;ll\n&gt;&gt; try to figure out what might have happened.\n&gt;\n&gt; Unfortunately I couldn&#39;t find any other exceptions or stack traces that\n&gt; might in\n&gt; any way explain this.\n&gt;\n&gt; Another crawl has run into what seems to be the same problem. Again I find\n&gt; that it corresponds exactly with a checkpoint event and this time I did\n&gt; spot the following in heritrix_out.log from around that time:\n&gt;\n&gt; 2010-08-19 03:05:10.120 SEVERE thread-84\n&gt; org.archive.crawler.framework.ToeThread.recoverableProblem() Problem\n&gt; java.lang.NegativeArraySizeException occured when trying to process\n&gt; &#39;http://www.spaug.is/images/dcsflashgames/Air_War.swf?pn_extravars=task~stor\n&gt; eScore&pn_modvar=option&pn_modvalue=com_dcs_flashgames&pn_uname=&pn_gid=110&\n&gt; pn_domain=http:&pn_license=&pn_checksum=4ad514bbcf3f985ca41965323d764fd5&#39; at\n&gt; step ABOUT_TO_BEGIN_PROCESSOR in\n&gt;\n&gt; java.lang.NegativeArraySizeException\n&gt;          at com.anotherbigidea.io.InStream.read(InStream.java:164)\n&gt;          at\n&gt; org.archive.modules.extractor.ExtractorSWF$ExtractorSWFReader.readOneTag(Ext\n&gt; ractorSWF.java:151)\n&gt;          at\n&gt; com.anotherbigidea.flash.readers.SWFReader.readTags(SWFReader.java:102)\n&gt;          at\n&gt; com.anotherbigidea.flash.readers.SWFReader.readFile(SWFReader.java:92)\n&gt;          at\n&gt; org.archive.modules.extractor.ExtractorSWF.innerExtract(ExtractorSWF.java:10\n&gt; 1)\n&gt;          at\n&gt; org.archive.modules.extractor.ContentExtractor.extract(ContentExtractor.java\n&gt; :36)\n&gt;          at\n&gt; org.archive.modules.extractor.Extractor.innerProcess(Extractor.java:95)\n&gt;          at\n&gt; org.archive.modules.Processor.innerProcessResult(Processor.java:177)\n&gt;          at org.archive.modules.Processor.process(Processor.java:144)\n&gt;          at\n&gt; org.archive.modules.ProcessorChain.process(ProcessorChain.java:131)\n&gt;          at org.archive.crawler.framework.ToeThread.run(ToeThread.java:146)\n&gt; not politeness-calc\n&gt;\n&gt; I&#39;m not really sure if this has anything to do with anything, and I&#39;ve\n&gt; observed the same error having occurred at least one time earlier in the\n&gt; crawl without having this effect.\n&gt;\n&gt; For now I&#39;m not trusting the checkpoint facility :(\n&gt;\n&gt; - Kris\n&gt;\n\n"}}