{"ygPerms":{"resourceCapabilityList":[{"resourceType":"GROUP","capabilities":[{"name":"READ"},{"name":"JOIN"}]},{"resourceType":"PHOTO","capabilities":[]},{"resourceType":"FILE","capabilities":[]},{"resourceType":"MEMBER","capabilities":[]},{"resourceType":"LINK","capabilities":[]},{"resourceType":"CALENDAR","capabilities":[]},{"resourceType":"DATABASE","capabilities":[]},{"resourceType":"POLL","capabilities":[]},{"resourceType":"MESSAGE","capabilities":[{"name":"READ"}]},{"resourceType":"PENDING_MESSAGE","capabilities":[]},{"resourceType":"ATTACHMENTS","capabilities":[{"name":"READ"}]},{"resourceType":"PHOTOMATIC_ALBUMS","capabilities":[]},{"resourceType":"MEMBERSHIP_TYPE","capabilities":[]},{"resourceType":"POST","capabilities":[{"name":"READ"}]},{"resourceType":"PIN","capabilities":[]}],"groupUrl":"groups.yahoo.com","intlCode":"us"},"comscore":"pageview_candidate","ygData":{"userId":137285340,"authorName":"Gordon Mohr","from":"Gordon Mohr &lt;gojomo@...&gt;","profile":"gojomo","replyTo":"LIST","senderId":"Skr0vnttOlBMv7g-rUYlue0nvHx6Dc6ajJ7vjaW3_jpXFnyBKNq5FZ3QevkiauiDnTUiiM4VWdZGiqO1jKju-CNGXq9zD08","spamInfo":{"isSpam":false,"reason":"6"},"subject":"Re: cannot recover from checkpoint","postDate":"1327025729","msgId":7543,"canDelete":false,"contentTrasformed":false,"systemMessage":false,"headers":{"messageIdInHeader":"PDRGMThDRTQxLjUwMDA4MDlAYXJjaGl2ZS5vcmc+","inReplyToHeader":"PDRGMTg4QTA5LjUwMDAwMDVAY3MuY211LmVkdT4=","referencesHeader":"PDRGMTcxQ0UyLjIwOTAwMDZAY3MuY211LmVkdT4gPDRGMTg4QTA5LjUwMDAwMDVAY3MuY211LmVkdT4="},"prevInTopic":7541,"nextInTopic":7544,"prevInTime":7542,"nextInTime":7544,"topicId":7532,"numMessagesInTopic":6,"msgSnippet":"I d overlooked this message when sending my previous message. Deleting the ?? keys is reasonable and would only mean a slight discrepancy in the running","rawEmail":"Return-Path: &lt;gojomo@...&gt;\r\nX-Sender: gojomo@...\r\nX-Apparently-To: archive-crawler@yahoogroups.com\r\nX-Received: (qmail 16961 invoked from network); 20 Jan 2012 02:15:32 -0000\r\nX-Received: from unknown (98.137.34.45)\n  by m16.grp.sp2.yahoo.com with QMQP; 20 Jan 2012 02:15:32 -0000\r\nX-Received: from unknown (HELO relay01.pair.com) (209.68.5.15)\n  by mta2.grp.sp2.yahoo.com with SMTP; 20 Jan 2012 02:15:31 -0000\r\nX-Received: (qmail 89204 invoked by uid 0); 20 Jan 2012 02:15:30 -0000\r\nX-Received: from 76.218.213.38 (HELO silverbook.local) (76.218.213.38)\n  by relay01.pair.com with SMTP; 20 Jan 2012 02:15:30 -0000\r\nX-pair-Authenticated: 76.218.213.38\r\nMessage-ID: &lt;4F18CE41.5000809@...&gt;\r\nDate: Thu, 19 Jan 2012 18:15:29 -0800\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:9.0) Gecko/20111222 Thunderbird/9.0.1\r\nMIME-Version: 1.0\r\nTo: David Pane &lt;dpane@...&gt;, archive-crawler@yahoogroups.com\r\nReferences: &lt;4F171CE2.2090006@...&gt; &lt;4F188A09.5000005@...&gt;\r\nIn-Reply-To: &lt;4F188A09.5000005@...&gt;\r\nContent-Type: text/plain; charset=ISO-8859-1; format=flowed\r\nContent-Transfer-Encoding: 7bit\r\nX-eGroups-Msg-Info: 1:6:0:0:0\r\nFrom: Gordon Mohr &lt;gojomo@...&gt;\r\nSubject: Re: cannot recover from checkpoint\r\nX-Yahoo-Group-Post: member; u=137285340; y=7X9urrxnX_yi-DPLQh4y-l0vSAUek1B6VkAfrATF8J2z\r\nX-Yahoo-Profile: gojomo\r\n\r\nI&#39;d overlooked this message when sending my previous message. Deleting \nthe &quot;??&quot; keys is reasonable and would only mean a slight discrepancy in \nthe running statistics.\n\nThe WARNINGs about a size larger than expected should be harmless; that \ndiscrepancy is an aftereffect of the last log file having one size as of \nthe time of the checkpoint, and then unavoidably growing as the crawl \ncontinues after that point.\n\nHowever, the errors about being unable to make links or delete files may \nbe an indication of some special difficulty on your system (perhaps due \nto OS load or filesystem issues).\n\nIf they are transient, then yes, clearing out the attempted restore and \ntrying again from the pristine checkpoint should be legitimate.\n\nYou *shouldn&#39;t* ever edit the manifest&#39;s idea of how log files are. \nThose were the accurate lengths at the time of the checkpoint; if the \nlast file was longer it will be truncated to match the desired size \nduring the resume, but any other discrepancies could mean fatal \ncorruption to the on-disk data stuctures. (Any missing data is probably \ndisasterous; a bit of extra data at then end might be survivable.)\n\n- Gordon\n\nOn 1/19/12 1:24 PM, David Pane wrote:\n&gt; I was finally able to get instance #1 restarted.\n&gt;\n&gt; Although I did a number of things before successfully restoring I\n&gt; believe that the main source of the failure was the duplicate key\n&gt; &quot;??text/javascript&quot; error&quot;. It is unclear what caused this duplicate\n&gt; key, but it appears that the following few checkpoints of the restarted\n&gt; instance dose not have this duplicate entry anymore.\n&gt;\n&gt;\n&gt; To ensure that I didn&#39;t corrupt the current state of the crawl state, I\n&gt; copied the following to a new directory /basepath/2011-12-23/.\n&gt;\n&gt; &quot;action&quot; directory\n&gt; &quot;checkpoints&quot; directory\n&gt; &quot;crawler-beans.cxml&quot; file\n&gt; &quot;diversions&quot; directory\n&gt; &quot;blacklist-optout.surt&quot; file\n&gt; &quot;seeds.txt&quot; file\n&gt;\n&gt; I created a the directory &quot;state&quot; and copied the desired recovery\n&gt; checkpoint directory from the original state directory into the newly\n&gt; create state directory.\n&gt;\n&gt; To eliminate the java.lang.RuntimeException: org.json.JSONException:\n&gt; Duplicate key &quot;??text/javascript&quot; error, I removed the second entry of\n&gt; of each of these:\n&gt; &quot;??text/javascript&quot;:1,\n&gt; &quot;??text/javascript&quot;:74208,\n&gt;\n&gt; from the file /path to jobs\n&gt; directory/2011-12-23/checkpoints/statisticsTracker\n&gt;\n&gt; Finally, I was having problems with a couple of files in the\n&gt; /path to jobs directory/2011-12-23/state/cp00001-201201xxxxxxxx directory.\n&gt;\n&gt; The filenames look like this &quot;000eb572.jdb,9999781&quot; where I think the\n&gt; 9999781 is suppose to represent the size of the file.\n&gt;\n&gt; WARNING thread-1ex6 org.archive.bdb.BdbModule.doRecover()\n&gt; 000eb572.jdb,9999781 expected 9999781 actual 9999838\n&gt; WARNING thread-16 org.archive.bdb.BdbModule.doRecover() 000eb572.jdb\n&gt; expected 9999781 actual 9999838\n&gt;\n&gt; Although these lines are not SEVER errors, I was wondering what would\n&gt; cause this?\n&gt;\n&gt;\n&gt; On several unsuccessful attempts on recovering from this copied\n&gt; checkpoint, I saw different files cause errors similar to this:\n&gt;\n&gt; SEVERE thread-12 org.archive.bdb.BdbModule.doRecover() unable to create\n&gt; required restore link /path to jobs directory/2011-12-23/state/000720e2.jdb\n&gt; SEVERE thread-16 org.archive.bdb.BdbModule.doRecover() unable to delete\n&gt; obstructing file /path to jobs directory/2011-12-23/state/0005915c.jdb\n&gt;\n&gt; In order to eliminate these SEVERE errors, I deleted the individual\n&gt; files *.jdb in the state directory. I also renamed the files in the\n&gt; checkpoint directory to represent the correct size. I modified the\n&gt; manifest file in that directory to represent the newly named file.\n&gt;\n&gt; Failed attempts to restore from this checkpoint appeared to cause the\n&gt; checkpoint files to change size and thus need to be renamed to avoid the\n&gt; warning of expected vs actual size as explained above.\n&gt;\n&gt;\n&gt; --David\n&gt;\n&gt; On 1/18/2012 2:26 PM, David Pane wrote:\n&gt;&gt; This morning I shut down all 5 instances. 4 recovered from the last\n&gt;&gt; checkpoint and are crawling. They are all running on less than\n&gt;&gt; configured threads due to the server errors I&#39;ve seen before.\n&gt;&gt;\n&gt;&gt; http://tech.groups.yahoo.com/group/archive-crawler/message/7493\n&gt;&gt;\n&gt;&gt; It is more severe than it was the last time.\n&gt;&gt;\n&gt;&gt; Instance #0 has 40 less - running with 1160.\n&gt;&gt; Instance #2 has 234 less - running with 234.\n&gt;&gt; Instance #3 has 111 less - running with 111.\n&gt;&gt; Instance #4 has 26 less - running with 26.\n&gt;&gt;\n&gt;&gt; -------------\n&gt;&gt; Instance #1:\n&gt;&gt; -------------\n&gt;&gt; When attempting to recover from &quot;any&quot; recent checkpoint, I get the\n&gt;&gt; following errors (see below) and the recover fails. Although this\n&gt;&gt; instance did not give me problems before, there were multiple SEVERE\n&gt;&gt; errors in the logs previous to me stopping the crawl. see attached file\n&gt;&gt; - I removed all INFO lines from the logs - sorry for the large\n&gt;&gt; attachment....\n&gt;&gt;\n&gt;&gt; I found that the mime-report has two entries for &quot;??text/javascript&quot;\n&gt;&gt;\n&gt;&gt; &gt;&gt;&gt; grep javascript mimetype-report.txt.2012-01-17h19m05\n&gt;&gt; 726509 15900289997 application/x-javascript\n&gt;&gt; 277744 5991936365 application/javascript\n&gt;&gt; 127275 3432127316 text/javascript\n&gt;&gt; 561 146075 text/javascript+json\n&gt;&gt; 272 7486875 text/x-javascript\n&gt;&gt; 24 142128 javascript/text\n&gt;&gt; 15 155529 javascript\n&gt;&gt; 10 191371 ?text/javascript?\n&gt;&gt; 6 175283 javascript/x-javascript\n&gt;&gt; 4 80925 application/vnd.javascript\n&gt;&gt; 3 193869 type/javascript\n&gt;&gt; 1 74208 ??text/javascript\n&gt;&gt; 1 33306 txt/javascript\n&gt;&gt; 1 74208 ??text/javascript\n&gt;&gt;\n&gt;&gt; I am also ready to start a recover from the frontier.recover but I am\n&gt;&gt; hoping that there is a way around this problem.... any ideas?????\n&gt;&gt;\n&gt;&gt; --David\n&gt;&gt;\n&gt;&gt; Here is a sample of what is in the logs.\n&gt;&gt;\n&gt;&gt; Job.log:\n&gt;&gt;\n&gt;&gt; 2012-01-18T17:37:39.992Z SEVERE Failed to start bean\n&gt;&gt; &#39;statisticsTracker&#39;; nested exception is java.lang.RuntimeException:\n&gt;&gt; org.json.JSONException: Duplicate key &quot;??text/javascript&quot; (in thread\n&gt;&gt; &#39;2011-12-23 launchthread&#39;)\n&gt;&gt; 2012-01-18T17:37:39.992Z SEVERE Failed to start bean\n&gt;&gt; &#39;statisticsTracker&#39;; nested exception is java.lang.RuntimeException:\n&gt;&gt; org.json.JSONException: Duplicate key &quot;??text/javascript&quot;\n&gt;&gt; 2012-01-18T17:37:39.990Z INFO Job instance discarded\n&gt;&gt; 2012-01-18T17:04:00.791Z SEVERE unable to delete obstructing file\n&gt;&gt; /scratch/heritrix-3.1.1/jobs/2011-12-23/state/00088669.jdb (in thread\n&gt;&gt; &#39;2011-12-23 launchthread&#39;)\n&gt;&gt; 2012-01-18T17:03:55.033Z SEVERE unable to create required restore link\n&gt;&gt; /scratch/heritrix-3.1.1/jobs/2011-12-23/state/00081efd.jdb (in thread\n&gt;&gt; &#39;2011-12-23 launchthread&#39;)\n&gt;&gt; 2012-01-18T17:02:18.458Z INFO Job launched\n&gt;&gt; 2012-01-18T16:59:19.283Z INFO Job instantiated\n&gt;&gt;\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; ---------------------------------------\n&gt;&gt; cat heritrix_out.log\n&gt;&gt;\n&gt;&gt; Wed Jan 18 11:59:05 EST 2012 Starting heritrix\n&gt;&gt; Linux compute-1-12.local 2.6.18-194.17.4.el5 #1 SMP Mon Oct 25 15:50:53\n&gt;&gt; EDT 2010 x86_64 GNU/Linux\n&gt;&gt; java version &quot;1.6.0_16&quot;\n&gt;&gt; Java(TM) SE Runtime Environment (build 1.6.0_16-b01)\n&gt;&gt; Java HotSpot(TM) 64-Bit Server VM (build 14.2-b01, mixed mode)\n&gt;&gt; JAVA_OPTS=-Xmx55000M\n&gt;&gt; core file size (blocks, -c) 0\n&gt;&gt; data seg size (kbytes, -d) unlimited\n&gt;&gt; scheduling priority (-e) 0\n&gt;&gt; file size (blocks, -f) unlimited\n&gt;&gt; pending signals (-i) 530432\n&gt;&gt; max locked memory (kbytes, -l) unlimited\n&gt;&gt; max memory size (kbytes, -m) unlimited\n&gt;&gt; open files (-n) 4096\n&gt;&gt; pipe size (512 bytes, -p) 8\n&gt;&gt; POSIX message queues (bytes, -q) 819200\n&gt;&gt; real-time priority (-r) 0\n&gt;&gt; stack size (kbytes, -s) unlimited\n&gt;&gt; cpu time (seconds, -t) unlimited\n&gt;&gt; max user processes (-u) 530432\n&gt;&gt; virtual memory (kbytes, -v) unlimited\n&gt;&gt; file locks (-x) unlimited\n&gt;&gt; Sun Microsystems Inc. Java(TM) SE Runtime Environment 1.6.0_16-b01\n&gt;&gt; Using ad-hoc HTTPS certificate with fingerprint...\n&gt;&gt; SHA1:7E:D5:A0:17:AD:CB:03:7D:4C:AD:FB:E7:04:41:AB:0B:1A:42:78:B3\n&gt;&gt; Verify in browser before accepting exception.\n&gt;&gt; 2012-01-18 16:59:05.737 WARNING thread-10\n&gt;&gt; org.archive.crawler.framework.Engine.findJobConfigs() invalid job\n&gt;&gt; directory: ./jobs/var where job expected from: ./jobs/var\n&gt;&gt; 2012-01-18 16:59:05.758 WARNING thread-10\n&gt;&gt; org.archive.crawler.framework.Engine.findJobConfigs() invalid job\n&gt;&gt; directory: ./jobs/heritrix_dir where job expected from:\n&gt;&gt; ./jobs/heritrix_dir\n&gt;&gt; 2012-01-18 16:59:05.892 INFO thread-10\n&gt;&gt; org.archive.crawler.framework.Engine.addJobDirectory() added crawl job:\n&gt;&gt; 2011-12-23\n&gt;&gt; 2012-01-18 16:59:05.893 WARNING thread-10\n&gt;&gt; org.archive.crawler.framework.Engine.findJobConfigs() invalid job\n&gt;&gt; directory: ./jobs/heritrix_out.logSAVE~ where job expected from:\n&gt;&gt; ./jobs/heritrix_out.logSAVE~\n&gt;&gt; 2012-01-18 16:59:05.893 WARNING thread-10\n&gt;&gt; org.archive.crawler.framework.Engine.findJobConfigs() invalid job\n&gt;&gt; directory: ./jobs/heritrix_out.logSAVE where job expected from:\n&gt;&gt; ./jobs/heritrix_out.logSAVE\n&gt;&gt; 2012-01-18 16:59:05.894 WARNING thread-10\n&gt;&gt; org.archive.crawler.framework.Engine.findJobConfigs() invalid job\n&gt;&gt; directory: ./jobs/heritrix_out.log20120118 where job expected from:\n&gt;&gt; ./jobs/heritrix_out.log20120118\n&gt;&gt; 2012-01-18 16:59:05.894 WARNING thread-10\n&gt;&gt; org.archive.crawler.framework.Engine.findJobConfigs() invalid job\n&gt;&gt; directory: ./jobs/heritrix_out.log20120118no-INFO where job expected\n&gt;&gt; from: ./jobs/heritrix_out.log20120118no-INFO\n&gt;&gt; 2012-01-18 16:59:06.04::INFO: Logging to STDERR via\n&gt;&gt; org.mortbay.log.StdErrLog\n&gt;&gt; 2012-01-18 16:59:06.05::INFO: jetty-6.1.14\n&gt;&gt; 2012-01-18 16:59:06.369::INFO: Started SslSocketConnector@10.1.1.249:8443\n&gt;&gt; engine listening at port 8443\n&gt;&gt; operator login set per file @...\n&gt;&gt; Heritrix version: 3.1.1-SNAPSHOT-20111222.225453\n&gt;&gt; 2012-01-18 16:59:17.201 INFO thread-11\n&gt;&gt; org.springframework.context.support.AbstractApplicationContext.prepareRefresh()\n&gt;&gt;\n&gt;&gt; Refreshing org.archive.spring.PathSharingContext@44ed904: startup date\n&gt;&gt; [Wed Jan 18 16:59:17 GMT 2012]; root of context hierarchy\n&gt;&gt; 2012-01-18 16:59:19.283 INFO thread-11\n&gt;&gt; org.archive.crawler.framework.CrawlJob.instantiateContainer() Job\n&gt;&gt; instantiated\n&gt;&gt; 2012-01-18 17:02:18.458 INFO thread-12\n&gt;&gt; org.archive.crawler.framework.CrawlJob.launch() Job launched\n&gt;&gt; 2012-01-18 17:02:19.997 INFO thread-13\n&gt;&gt; org.archive.spring.PathSharingContext.initLaunchId() launch id\n&gt;&gt; 20120118170219\n&gt;&gt; 2012-01-18 17:02:20.047 INFO thread-13\n&gt;&gt; org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start()\n&gt;&gt;\n&gt;&gt; Starting beans in phase 0\n&gt;&gt; 2012-01-18 17:03:55.033 SEVERE thread-13\n&gt;&gt; org.archive.bdb.BdbModule.doRecover() unable to create required restore\n&gt;&gt; link /scratch/heritrix-3.1.1/jobs/2011-12-23/state/00081efd.jdb\n&gt;&gt; 2012-01-18 17:04:00.791 SEVERE thread-13\n&gt;&gt; org.archive.bdb.BdbModule.doRecover() unable to delete obstructing file\n&gt;&gt; /scratch/heritrix-3.1.1/jobs/2011-12-23/state/00088669.jdb\n&gt;&gt; 2012-01-18 17:34:12.297 INFO thread-13\n&gt;&gt; org.springframework.context.support.AbstractApplicationContext.doClose()\n&gt;&gt; Closing org.archive.spring.PathSharingContext@44ed904: startup date [Wed\n&gt;&gt; Jan 18 16:59:17 GMT 2012]; root of context hierarchy\n&gt;&gt; 2012-01-18 17:34:12.298 INFO thread-13\n&gt;&gt; org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop()\n&gt;&gt;\n&gt;&gt; Stopping beans in phase 0\n&gt;&gt; 2012-01-18 17:37:39.990 INFO thread-13\n&gt;&gt; org.archive.crawler.framework.CrawlJob.doTeardown() Job instance\n&gt;&gt; discarded\n&gt;&gt; 2012-01-18 17:37:39.992 SEVERE thread-13\n&gt;&gt; org.archive.crawler.framework.CrawlJob.beansException() Failed to start\n&gt;&gt; bean &#39;statisticsTracker&#39;; nested exception is\n&gt;&gt; java.lang.RuntimeException: org.json.JSONException: Duplicate key\n&gt;&gt; &quot;??text/javascript&quot;\n&gt;&gt; org.springframework.context.ApplicationContextException: Failed to start\n&gt;&gt; bean &#39;statisticsTracker&#39;; nested exception is\n&gt;&gt; java.lang.RuntimeException: org.json.JSONException: Duplicate key\n&gt;&gt; &quot;??text/javascript&quot;\n&gt;&gt; at\n&gt;&gt; org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:169)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:159)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:159)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:159)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.context.support.DefaultLifecycleProcessor.access$1(DefaultLifecycleProcessor.java:154)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:335)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:143)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.context.support.DefaultLifecycleProcessor.start(DefaultLifecycleProcessor.java:89)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.context.support.AbstractApplicationContext.start(AbstractApplicationContext.java:1236)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.archive.spring.PathSharingContext.start(PathSharingContext.java:112)\n&gt;&gt; at org.archive.crawler.framework.CrawlJob.startContext(CrawlJob.java:458)\n&gt;&gt; at org.archive.crawler.framework.CrawlJob$1.run(CrawlJob.java:432)\n&gt;&gt; Caused by: java.lang.RuntimeException: org.json.JSONException: Duplicate\n&gt;&gt; key &quot;??text/javascript&quot;\n&gt;&gt; at org.archive.checkpointing.Checkpoint.loadJson(Checkpoint.java:142)\n&gt;&gt; at\n&gt;&gt; org.archive.crawler.reporting.StatisticsTracker.start(StatisticsTracker.java:355)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:166)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; ... 11 more\n&gt;&gt; Caused by: org.json.JSONException: Duplicate key &quot;??text/javascript&quot;\n&gt;&gt; at org.json.JSONObject.putOnce(JSONObject.java:1076)\n&gt;&gt; at org.json.JSONObject.&lt;init&gt;(JSONObject.java:205)\n&gt;&gt; at org.json.JSONTokener.nextValue(JSONTokener.java:344)\n&gt;&gt; at org.json.JSONObject.&lt;init&gt;(JSONObject.java:205)\n&gt;&gt; at org.json.JSONObject.&lt;init&gt;(JSONObject.java:402)\n&gt;&gt; at org.archive.checkpointing.Checkpoint.loadJson(Checkpoint.java:140)\n&gt;&gt; ... 13 more\n&gt;&gt; Exception in thread &quot;2011-12-23 launchthread&quot;\n&gt;&gt; org.springframework.beans.factory.BeanCreationException: Error creating\n&gt;&gt; bean with name &#39;configPathConfigurer&#39; defined in URL\n&gt;&gt; [file:/scratch/heritrix-3.1.1/jobs/2011-12-23/crawler-beans.cxml]:\n&gt;&gt; Initialization of bean failed; nested exception is\n&gt;&gt; java.lang.IllegalStateException: BeanFactory not initialized or already\n&gt;&gt; closed - call &#39;refresh&#39; before accessing beans via the ApplicationContext\n&gt;&gt; at\n&gt;&gt; org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:527)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.context.event.AbstractApplicationEventMulticaster.getApplicationListeners(AbstractApplicationEventMulticaster.java:148)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:86)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:303)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.archive.crawler.framework.CrawlController.sendCrawlStateChangeEvent(CrawlController.java:326)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.archive.crawler.framework.CrawlController.requestCrawlStart(CrawlController.java:347)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at org.archive.crawler.framework.CrawlJob$1.run(CrawlJob.java:434)\n&gt;&gt; Caused by: java.lang.IllegalStateException: BeanFactory not initialized\n&gt;&gt; or already closed - call &#39;refresh&#39; before accessing beans via the\n&gt;&gt; ApplicationContext\n&gt;&gt; at\n&gt;&gt; org.springframework.context.support.AbstractRefreshableApplicationContext.getBeanFactory(AbstractRefreshableApplicationContext.java:171)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.context.support.AbstractApplicationContext.containsBean(AbstractApplicationContext.java:1091)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.context.support.AbstractApplicationContext$ApplicationListenerDetector.postProcessAfterInitialization(AbstractApplicationContext.java:1369)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:407)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1426)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; at\n&gt;&gt; org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)\n&gt;&gt;\n&gt;&gt;\n&gt;&gt; ... 11 more\n\n"}}